name: Deploy Application on cPanel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        run: |
          ssh ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd /home/mokushiken/repositories/Mokushi-Api/Mokushi-Backend
          git pull origin production
          source /home/mokushiken/nodevenv/repositories/Mokushi-Api/Mokushi-Backend/20/bin/activate && cd /home/mokushiken/repositories/Mokushi-Api/Mokushi-Backend
          npm install
          npx prisma generate
          cloudlinux-selector restart --user mokushiken --interpreter nodejs --app-root /home/mokushiken/repositories/Mokushi-Api/Mokushi-Backend --json
          EOF
